### ISSUE TITLE
[BlueBubbles] Shared links split text/preview/website favicon

### ISSUE THREAD

**Issue by jamestalbot3** [mautrix/imessage#204] opened 2024-03-24 19:59 UTC
Just set up the bridge with bluebubbles yesterday and am running into an issue where anytime somebody shares a link in a group chat, it splits the link into three separate messages. The first one is the website favicon sent as an image, the second is an image from a rich link preview, and the third is the actual link and associated text. Any tapback reactions to the text is attached to the favicon text. 

![image](https://github.com/mautrix/imessage/assets/68798318/8ef08901-e96d-464c-a5b0-6ca782ab958b)

**Comment by trek-boldly-go** [comment] 2024-03-25 14:15
Duplicate of #183

**Closed by trek-boldly-go** 2024-03-25 14:15 UTC
Labels: bug

**Comment by illgitthat** [comment] 2024-11-11 03:28
@trek-boldly-go are you sure this is a duplicate of #183 ?

From my understanding, #183 is about an attachment with error message being generated.

This issue is about additional media being attached from fetched open graph meta tags.

I personally still have this issue as described by @jamestalbot3 and would like to see this issue reopened.

Please let me know if I should open another issue instead.

Example:
![image](https://github.com/user-attachments/assets/69cae727-26b8-475e-925d-aca95ca2b91e)
